version: '3'

services:
  app:
    container_name: application_server
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh node index.js
    build:
      context: ./nginx-with-nodejs
      dockerfile: Dockerfile
    networks:
      - node_network
    volumes:
      - ./nginx-with-nodejs/:/usr/src/app/
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: mysql_database
    restart: always
    tty: true
    volumes: 
    - ./mysql:/var/lib/mysql
    - ./sql:/data/application
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
    - node_network

  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    ports: 
    - "8080:8080"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - node_network

networks:
  node_network:
    driver: bridge